### ISSUE TITLE
Failed to load book dehydration:dehydration defined by mod dehydration, skipping

### ISSUE THREAD

**Issue by erylflynn** [Globox1997/Dehydration#137]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.22

### Mod Version

1.3.4-1

### Describe the Issue

Mod fails to load, we see errors in the log.  I have tried with Java 1.17 and 1.20 no change in behavior.  

This is where I think the issue is but do not know how to fix.
Error loading class: net/minecraft/class_5684

### latest.log

[13:51:19 INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.22
[13:51:19 INFO]: Loading 50 mods:
	- aquamirae 6
	- cloth-config 11.1.106
	   \-- cloth-basic-math 0.6.1
	- dehydration 1.3.4
	- fabric-api 0.87.0+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.9+e022e5d177
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.9+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.2.2+1e61dba177
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.10+23d9108177
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.39+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.43+9e7660c677
	   |-- fabric-message-api-v1 5.1.7+3265161977
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.1+6beca84877
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.1.2+6bdb2ed077
	   |-- fabric-renderer-indigo 1.4.2+6bdb2ed077
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.34+b3afc78b77
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.0+cdf060b277
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabricloader 0.14.22
	- geckolib 4.2.2
	   \-- com_eliotlash_mclib_mclib 20
	- java 17
	- minecraft 1.20.1
	- obscure_api 16
	- patchouli 1.20.1-81-FABRIC
	   \-- fiber 0.23.0-2
[13:51:19 INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Eryl%20Flynn/Desktop/Minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[13:51:19 INFO]: Compatibility level set to JAVA_17
[13:51:20 WARN]: Error loading class: net/minecraft/class_5684 (java.lang.ClassNotFoundException: net/minecraft/class_5684)
[13:51:20 WARN]: @Mixin target net.minecraft.class_5684 was not found dehydration.mixins.json:TooltipComponentMixin from mod dehydration
[13:51:27 ERROR]: Failed to load book dehydration:dehydration defined by mod dehydration, skipping
java.lang.IllegalArgumentException: Book dehydration:dehydration has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
	at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.fabric.common.FabricModInitializer.onInitialize(FabricModInitializer.java:33) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.22.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.14.22-launcher.0.11.2.jar:0.11.2]
[13:51:27 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:51:28 INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[13:51:29 INFO]: Loaded 7 recipes
[13:51:29 INFO]: Loaded 1308 advancements
[13:51:30 INFO]: Applied 9 biome modifications to 1 of 64 new biomes in 10.07 ms
[13:51:30 INFO]: Starting minecraft server version 1.20.1
[13:51:30 INFO]: Loading properties
[13:51:30 INFO]: Default game type: CREATIVE
[13:51:30 INFO]: Generating keypair
[13:51:30 INFO]: Starting Minecraft server on *:25565
[13:51:30 INFO]: Using default channel type
[13:51:31 INFO]: Preparing level "world"
[13:51:32 INFO]: Preparing start region for dimension minecraft:overworld
[13:51:34 INFO]: Preparing spawn area: 0%
[13:51:34 INFO]: Preparing spawn area: 0%
[13:51:34 INFO]: Preparing spawn area: 0%
[13:51:34 INFO]: Preparing spawn area: 0%
[13:51:34 INFO]: Preparing spawn area: 0%
[13:51:34 INFO]: Preparing spawn area: 0%
[13:51:35 INFO]: Preparing spawn area: 56%
[13:51:37 INFO]: Time elapsed: 5029 ms
[13:51:37 INFO]: Done (6.472s)! For help, type "help"

### Do you use any other mods except the required ones?

Yes but they are new.

**Comment by erylflynn** [comment]
Did try fresh serve with just Dehydration and required addons.  No change

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/Dehydration/commit/88e67485745d374488d9ea2f9837c0518b339b99](https://github.com/Globox1997/Dehydration/commit/88e67485745d374488d9ea2f9837c0518b339b99)
