### ISSUE TITLE
Game crashes as dispenser overfills copper cauldron with purified water

### ISSUE THREAD

**Issue by dudematthew** [Globox1997/Dehydration#153]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.3

### Mod Version

1.3.5

### Describe the Issue

To reproduce fill dispenser with purified water buckets, then activate it twice facing copper cauldron. If cauldron has already some water, trying to fill it will crash the game. I suppose it should imitate similar behaviour as normal water and cauldron.

### latest.log

[02:55:18] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_2315 cannot be cast to class net.dehydration.block.CopperLeveledCauldronBlock (net.minecraft.class_2315 and net.dehydration.block.CopperLeveledCauldronBlock are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3bfdc050)
	at net.minecraft.class_2315.handler$can000$dehydration$dispenseMixin(class_2315.java:565) ~[client-intermediary.jar:?]
	at net.minecraft.class_2315.method_10012(class_2315.java:86) ~[client-intermediary.jar:?]
	at net.minecraft.class_2315.method_9588(class_2315.java:113) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:1113) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_14189(class_3218.java:728) ~[client-intermediary.jar:?]
	at net.minecraft.class_6757.method_39390(class_6757.java:215) ~[client-intermediary.jar:?]
	at net.minecraft.class_6757.method_39377(class_6757.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:323) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[client-intermediary.jar:?]
	... 5 more
[02:55:18] [Server thread/ERROR]: This crash report has been saved to: E:\Program Files\MultiMC\instances\1.20.1\.minecraft\crash-reports\crash-2024-01-19_02.55.18-server.txt
[02:55:18] [Server thread/INFO]: [STDOUT]: Saving server results
[02:55:18] [Server thread/INFO]: Stopping server
[02:55:18] [Server thread/INFO]: Saving players
---- Minecraft Crash Report ----
// My bad.

Time: 2024-01-19 02:55:18
Description: Exception ticking world

java.lang.ClassCastException: class net.minecraft.class_2315 cannot be cast to class net.dehydration.block.CopperLeveledCauldronBlock (net.minecraft.class_2315 and net.dehydration.block.CopperLeveledCauldronBlock are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3bfdc050)
	at net.minecraft.class_2315.handler$can000$dehydration$dispenseMixin(class_2315.java:565)
	at net.minecraft.class_2315.method_10012(class_2315.java:86)
	at net.minecraft.class_2315.method_9588(class_2315.java:113)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:1113)
	at net.minecraft.class_3218.method_14189(class_3218.java:728)
	at net.minecraft.class_6757.method_39390(class_6757.java:215)
	at net.minecraft.class_6757.method_39377(class_6757.java:98)
	at net.minecraft.class_3218.method_18765(class_3218.java:323)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:842)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2315.handler$can000$dehydration$dispenseMixin(class_2315.java:565)
	at net.minecraft.class_2315.method_10012(class_2315.java:86)
	at net.minecraft.class_2315.method_9588(class_2315.java:113)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:1113)
	at net.minecraft.class_3218.method_14189(class_3218.java:728)
	at net.minecraft.class_6757.method_39390(class_6757.java:215)
	at net.minecraft.class_6757.method_39377(class_6757.java:98)
	at net.minecraft.class_3218.method_18765(class_3218.java:323)

-- Affected level --
Details:
	All players: 1 total; [class_3222['HippieSavage'/11, l='ServerLevel[Hypis Chujnia]', x=-80.12, y=8.00, z=1229.64]]
	Chunk stats: 4610
	Level dimension: minecraft:overworld
	Level spawn location: World: (-96,69,272), Section: (at 0,5,0 in -6,4,17; chunk contains blocks -96,-64,272 to -81,319,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 2349895 game time, 1421417 day time
	Level name: Hypis Chujnia
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:842)

### Do you use any other mods except the required ones?

Yes, but I'm sorry, no time for testing without them. Hope I haven't wasted your time.

**Comment by Globox1997** [comment]
Thanks for the report, fixed with [https://github.com/Globox1997/Dehydration/commit/bb48fc9ed0d2838d12d370409640b28fff4fa063](https://github.com/Globox1997/Dehydration/commit/bb48fc9ed0d2838d12d370409640b28fff4fa063)
