### ISSUE TITLE
Crash on opening chests containing certain modded potions

### ISSUE THREAD

**Issue by Thurinum** [Globox1997/Dehydration#190]
### Minecraft Version

1.21.x

### Mod Loader Version

0.16.2

### Mod Version

1.3.7

### Describe the Issue

The game crashes when an inventory screen (player, chest) that contains certain custom potions is opened, such as this one:

![image](https://github.com/user-attachments/assets/9f2c2040-6319-47a2-9874-2291dfbebe34)

Disabling Dehydration solves the issue and allows the potions to be interacted with normally. I think those potions are specific to the Roguelike dungeons mod, as I've never seen them anywhere else (and the game doesn't crashes anywhere else to my knowledge). They look like a regular minecraft:potion stacking multiple effects and with a custom tooltip. 

Here's the stack trace:
```
net.minecraft.class_148: Exception ticking world
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1025) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Unknown Source) ~[?:?]
	at net.minecraft.class_2315.handler$bjl000$dehydration$dispenseMixin(class_2315.java:572) ~[client-intermediary.jar:?]
	at net.minecraft.class_2315.method_10012(class_2315.java:106) ~[client-intermediary.jar:?]
	at net.minecraft.class_2315.method_9588(class_2315.java:136) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:1149) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_14189(class_3218.java:759) ~[client-intermediary.jar:?]
	at net.minecraft.class_6757.method_39390(class_6757.java:215) ~[client-intermediary.jar:?]
	at net.minecraft.class_6757.method_39377(class_6757.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:339) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021) ~[client-intermediary.jar:?]
	... 5 more
[20:59:08] [Server thread/ERROR]: This crash report has been saved to: G:\Games\Modrinth\profiles\Arwindale 2\crash-reports\crash-2024-09-04_20.59.08-server.txt
```

Great mod btw!

### latest.log

[2024-09-04-5.log](https://github.com/user-attachments/files/16882572/2024-09-04-5.log)

### Do you use any other mods except the required ones?

Quite a lot, list is in the logs.

**Comment by Globox1997** [comment]
Thanks for the report, fixed with [https://github.com/Globox1997/Dehydration/commit/5d5d2f2bc770ca33644cc7127622fea6081dc4df](https://github.com/Globox1997/Dehydration/commit/5d5d2f2bc770ca33644cc7127622fea6081dc4df)
