### ISSUE TITLE
Incompatible / crash with Auto HUD

### ISSUE THREAD

**Issue by rght925h** [Globox1997/Dehydration#191]
### Minecraft Version

1.21.x

### Mod Loader Version

0.16.5-1.21.1

### Mod Version

dehydration-1.3.7+1.21.1

### Describe the Issue

A crash occurs when loading in as client, running dehydration-1.3.7+1.21.1 and Auto HUD 7.2.1.

### latest.log

```
[Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchFieldError: Class net.dehydration.init.EffectInit does not have member field 'net.minecraft.class_1291 THIRST'
	at mod.crend.autohud.compat.DehydrationCompat.tickState(DehydrationCompat.java:46) ~[autohud-7.2.1+1.21-fabric.jar:?]
	at mod.crend.autohud.component.State.lambda$tick$8(State.java:157) ~[autohud-7.2.1+1.21-fabric.jar:?]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at mod.crend.autohud.component.State.tick(State.java:157) ~[autohud-7.2.1+1.21-fabric.jar:?]
	at mod.crend.autohud.component.Hud.tickState(Hud.java:49) ~[autohud-7.2.1+1.21-fabric.jar:?]
	at mod.crend.libbamboo.event.ClientEventHandler.tick(ClientEventHandler.java:219) ~[libbamboo-1.21.0.2-dcf068e4ba1d5913.jar:?]
	at mod.crend.libbamboo.fabric.LibBambooMod.lambda$onInitializeClient$0(LibBambooMod.java:12) ~[libbamboo-1.21.0.2-dcf068e4ba1d5913.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43) ~[fabric-lifecycle-events-v1-2.3.1+6c1df36019-f08a967dd320d5f1.jar:?]
	at net.minecraft.class_310.handler$ddd000$fabric-lifecycle-events-v1$onEndTick(class_310.java:15683) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2012) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1246) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.5.jar:?]
```

### Do you use any other mods except the required ones?

Auto HUD

**Comment by Globox1997** [comment]
Seems like there is already a compat on autohuds side.
Can't do something from here, it has to get updated from autohuds side.
