### ISSUE TITLE
Campfire Cauldron crashes world when filling with water

### ISSUE THREAD

**Issue by graysenpack** [Globox1997/Dehydration#52]
I think this may be a conflict with Sodium/Iris, but I'm not 100% sure.  I put the Campfire Cauldron over a campfire, then when I try to fill it with a water bucket the game crashes. When loaded back, about 50% of the blocks in the world are transparent. If I remove the water & reload the textures it fixes it. Putting the water back in again starts the cycle over. Attaching a crash report.

**CRASH LOG**
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 10/9/21, 9:57 PM
Description: Unexpected error

java.util.concurrent.CompletionException: java.lang.ClassCastException: class net.minecraft.class_2595 cannot be cast to class net.dehydration.block.entity.CampfireCauldronEntity (net.minecraft.class_2595 and net.dehydration.block.entity.CampfireCauldronEntity are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @141e5bef)
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2114)
	at me.jellysquid.mods.sodium.common.util.collections.FutureQueueDrainingIterator.findNext(FutureQueueDrainingIterator.java:35)
	at me.jellysquid.mods.sodium.common.util.collections.FutureQueueDrainingIterator.hasNext(FutureQueueDrainingIterator.java:25)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.setupUploadBatches(RenderRegionManager.java:128)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:64)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:371)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:220)
	at net.minecraft.class_761.method_3273(class_761.java:4344)
	at net.minecraft.class_761.method_22710(class_761.java:1142)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.ClassCastException: class net.minecraft.class_2595 cannot be cast to class net.dehydration.block.entity.CampfireCauldronEntity (net.minecraft.class_2595 and net.dehydration.block.entity.CampfireCauldronEntity are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @141e5bef)
	at net.dehydration.block.CampfireCauldronBlock.isPurifiedWater(CampfireCauldronBlock.java:254)
	at net.dehydration.init.RenderInit.isPurifiedWater(RenderInit.java:29)
	at net.dehydration.init.RenderInit.lambda$init$0(RenderInit.java:15)
	at me.jellysquid.mods.sodium.client.model.quad.blender.SmoothBiomeColorBlender.getBlockColor(SmoothBiomeColorBlender.java:46)
	at me.jellysquid.mods.sodium.client.model.quad.blender.SmoothBiomeColorBlender.getInterpolatedVertexColor(SmoothBiomeColorBlender.java:63)
	at me.jellysquid.mods.sodium.client.model.quad.blender.SmoothBiomeColorBlender.getColors(SmoothBiomeColorBlender.java:27)
	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderQuad(BlockRenderer.java:132)
	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderQuadList(BlockRenderer.java:118)
	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:78)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:100)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.processJob(ChunkBuilder.java:235)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:220)
	at java.base/java.lang.Thread.run(Thread.java:831)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2114)
	at me.jellysquid.mods.sodium.common.util.collections.FutureQueueDrainingIterator.findNext(FutureQueueDrainingIterator.java:35)
	at me.jellysquid.mods.sodium.common.util.collections.FutureQueueDrainingIterator.hasNext(FutureQueueDrainingIterator.java:25)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.setupUploadBatches(RenderRegionManager.java:128)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:64)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:371)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:220)
	at net.minecraft.class_761.method_3273(class_761.java:4344)
	at net.minecraft.class_761.method_22710(class_761.java:1142)
	at net.minecraft.class_757.method_3188(class_757.java:1026)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$beo000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Affected level --
Details:
	All players: 1 total; [class_746['graypax'/7420, l='ClientLevel', x=-125.49, y=64.00, z=36.53]]
	Chunk stats: 1024, 675
	Level dimension: minecraft:overworld
	Level spawn location: World: (-150,66,12), Section: (at 10,2,12 in -10,4,0; chunk contains blocks -160,0,0 to -145,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2258102 game time, 2364660 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 6317510000 bytes (6024 MiB) / 7918845952 bytes (7552 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7212
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.00
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.00
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37564.56
	Virtual memory used (MB): 22163.40
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 10.87
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancedcompass: Advanced Compass 1.2.3
		adventurez: AdventureZ 1.3.0
		amecsapi: Amecs API 1.1.5+mc21w16a
		antiqueatlas: Antique Atlas 6.1.0-fabric-mc1.17.1
		architectury: Architectury 2.5.30
		backslot: BackSlot 1.2.1
		backslotaddon: BackSlot Addon 1.0.6
		bclib: BCLib 0.3.1
		betterend: Better End 0.11.0-pre
		betternether: Better Nether 5.1.3
		biomeinfo: Biome Info 1.17-7
		boatcontainer: BoatContainer 1.0.0
		bountiful: Bountiful 1.0.0
		cameraoverhaul: Camera Overhaul 1.2.2-fabric-universal
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		comforts: Comforts 0.0.7-1.17.1
		cool_elytra: Cool Elytra 1.2.1
		crowdin-translate: CrowdinTranslate 1.3+1.17
		dehydration: Dehydration 1.2.4
		drinkbeer: Drink Beer 2.2
		dualwielding: Dual Wielding 1.0.6
		eldritch_mobs: Eldritch Mobs 1.9.6
		enchantment_lore: EnchantmentLore 1.2.1+MC1.17.1
		endrem: End Remastered 4.1.0
		enhancedcelestials: Enhanced Celestials 2.0.5
		environmentz: EnvironmentZ 1.1.6
		fabric: Fabric API 0.40.6+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.11+7931163218
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.4+7931163218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.5+7931163218
		fabric-rendering-v1: Fabric Rendering (v1) 1.9.0+7931163218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.0+7931163218
		fabricloader: Fabric Loader 0.11.6
		fallingleaves: Falling Leaves 1.7.3+1.17.1
		fiber: fiber 0.23.0-2
		geckolib3: Geckolib 3.0.15
		graveyard: The Graveyard 1.0
		hookshot: Hookshot 20.0
		illuminations: Illuminations 1.8
		inventoryhud: Inventory HUD + 3.4.0
		inventoryprofilesnext: Inventory Profiles Next 0.8.0
		iris: Iris 1.1.2+build.9
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kambrik: Kambrik 1.1.0
		levelz: LevelZ 1.0.12
		libgui: LibGui 4.1.6+1.17.1
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.2.1+1.17
		lovely_snails: Lovely Snails 1.0.3+1.17
		malilib: MaLiLib 0.10.0-dev.24
		minecraft: Minecraft 1.17.1
		minihud: MiniHUD 0.19.0-dev.20210609.185508
		mm: Manningham Mills 2.2
		modmenu: Mod Menu 2.0.14
		mythic-mounts: Mythic Mounts 1.17.1-1.3
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		patchouli: Patchouli 1.17-54-FABRIC
		physicsmod: Physics Mod 2.5.7
		roughlyenoughitems: Roughly Enough Items 6.0.279-alpha
		seasons: Fabric Seasons 1.3-BETA+1.17
		shulkerboxtooltip: Shulker Box Tooltip 3.0.0+1.17
		skinlayers: 3d Skin Layers 1.1.0
		sodium: Sodium 0.3.2+IRIS2-build.9
		somnus: Somnus API 0.0.13-1.17.1
		spruceui: SpruceUI 3.2.0+1.17
		torohealth: ToroHealth Damage Indicators 1.17.1-fabric-12
		voxelmap: VoxelMap 1.10.15
		waystones: Waystones 2.1.2
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 472.12, NVIDIA Corporation
	Window size: 3840x2066
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 6x Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz

**Comment by Globox1997** [comment]
[dehydration-1.2.5.zip](https://github.com/Globox1997/Dehydration/files/7320486/dehydration-1.2.5.zip)
Can you test this? you have to unzip the file
